#! /bin/sh
# /etc/init.d/powermon

### BEGIN INIT INFO
# Provides:          powermon
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start the powermon program
# Description:       powermon provides the http://your_web_site_url site works with start and stop only
### END INIT INFO

# run every time commands here

# none

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting powermon"
    # run application you want to start 
    /home/pi/currentcost/bin/start
    ;;
  stop)
    echo "Stopping powermon"
    # kill application you want to stop
    killall get_data_rrd.py
    ;;
  *)
    echo "Usage: /etc/init.d/powermon {start|stop}"
    exit 1
    ;;
esac

exit 0
